### ISSUE TITLE
Data Gathering

### ISSUE THREAD

**Issue by tonycsoka** [tonycsoka/ostmodern#1]
Import all episodes of all seasons of Game Of Thrones from OMDb API.

- [x] Get API Key from [OMDb](http://www.omdbapi.com/apikey.aspx) See Issue #7  
- [ ] Write common code to grab data from OMDb See Issue #9  
- [ ] Get series info from [http://www.omdbapi.com/?t=Game of Thrones&Season=1&apikey=](http://www.omdbapi.com/?t=Game%20of%20Thrones&Season=1&apikey=) Issue #8 
- [ ] Get episode info from [http://www.omdbapi.com/?i=&apikey=](http://www.omdbapi.com/?i=&apikey=)
